project:
  type: website

website:
  navbar:
    left:
      - href: index.qmd
        text: HOME
      - href: projects.qmd
        text: PROJECTS
      - href: coursework.qmd
        text: COURSEWORK

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


execute: 
  freeze: auto
