---
#title: "Coursework"
---

## Relevant Coursework at UCLA


##### Mathematics

- Math 115A: Linear Algebra
- Math 131A: Analysis 
- Math 132: Complex Analysis for Applications
- Math 151A: Applied Numerical Methods Part 1
- Math 151B: Applied Numerical Methods Part 2 *(Spring 2024)*
- Math 174E: Mathematics of Finance for Mathematics/Economics Students
- Math 32A: Calculus of Several Variables
- Math 32B: Calculus of Several Variables
- Math 33A: Linear Algebra and Applications
- Math 33B: Differential Equations
- Math 42: Data-Driven Mathematical Modeling
- Math 61: Discrete Structures

##### Statistics

- Math 170E: Probability and Statistics: Part 1 Probability
- Math 170S: Probability and Statistics: Part 2 Statistics
- Stats 100C: Linear Models
- Stats 101A: Data Analysis and Regression
- Stats 101B: Design and Analysis of Experiment
- Stats 101C: Statistical Models and Data Mining
- Stats 102A: Data Analysis and Regression
- Stats 102B: Design and Analysis of Experiment *(Spring 2024)*
- Stats 102C: Statistical Models and Data Mining *(Fall 2024)*
- Stats 140XP: Practice of Statistical Consulting I 
- Stats 141XP: Practice of Statistical Consulting II *(Spring 2024)*
- Stats C183: Statistical Models in Finance
- Stats 10: Statistical Reasoning
- Stats 20: Statistical Programming with R
- Stats 21: Python and Other Technologies for Data Science

##### Computer Science
- CS C122: Algorithms in Computational Genomics
- CS M146: Introduction to Machine Learning
- CS M148: Introduction to Data Science
- CS 31: Introduction to Computer Science I (C++)
- CS 32: Introduction to Computer Science II (C++)
- CS 33: Introduction to Computer Organization
- CS 35L: Software Construction

